### ISSUE TITLE
funny gunzip-maybe bug

### ISSUE THREAD

**Issue by chpio** [mafintosh/gunzip-maybe#3]
hi,

i encountered a bug with this package:

* if i use gunzip-maybe the output stops after a few files
* if i pre-unzip (gunzip-maybe or gzip cli command) the file everything goes well

https://gist.github.com/chpio/6d0cedae59d8416d0aed

**Comment by chpio** [comment]
```javascript
require('fs').createReadStream('./test.tgz')
	.pipe(require('zlib').createGunzip())
	.pipe(require('tar-stream').extract())
	.on('entry', (e, content, next) => {
		console.log(e);
		next();
	});
```

fails too. i would say, it's a tar-stream or zlib bug

**Comment by mafintosh** [comment]
did you figure out what the bug was?
