### ISSUE TITLE
Add other formats?

### ISSUE THREAD

**Issue by piranna** [mafintosh/gunzip-maybe#4]
I'm interested on decompress bzip2 files... or not. Does it makes sense to add that checking on `gunzip-maybe`, or do you think it's better I create a new `bzip2-maybe` module and chain them one after another? Does it makes sense to create a generic `maybe` module that has the common parts of `gunzip-maybe` and `bzip2-maybe` modules?

**Comment by mafintosh** [comment]
I'd make a new module and just pipe it through both. A generic decompress-maybe that just uses pumpify to combine the two makes sense as well 👍

**Comment by piranna** [comment]
Ok, thanks :-)

**Comment by piranna** [comment]
https://github.com/piranna/bzip2-maybe

I thought you would ve interested ;-) I've used gunzip-maybe as basis :-)

**Comment by mafintosh** [comment]
N I C E

**Comment by mafintosh** [comment]
as a token of appreciation i present to you, this idea for the source of a decompress-maybe module (that you should publish)

``` js
module.exports = function () {
  return pumpify(bzipMaybe(), gunzipMaybe())
}
```

**Comment by piranna** [comment]
Lol :-P  Yeah, definitely an easy and useful one ;-) I'll do it :-D

**Comment by piranna** [comment]
And... [published](https://www.npmjs.com/package/decompress-maybe)!!! :-D

It's not the way I would have been asking for because  `gunzip-maybe` allow recursive compressed files (a gz inside a gz) and I did it the same way on `bzip2-maybe`. `decompress-maybe` don't support it yet and would need some work on both `bzip2-maybe` and `gunzip-maybe` to allow it to be `(bzip2|gunzip)*`instead of `(bzip2*|gunzip*)*` as it would be now (regular expressions syntax), but definitely is a good starting point, if we get other formtats in the future we can review it to optimize :-)
